Repository caicloud/katib, pull requests merged in 2019-05, with the labels that each got.

#2 feat: Add experiment controller
  examples/v1alpha2/random-example.yaml
  pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
  pkg/controller/v1alpha3/experiment/clientset/trial.go
  pkg/controller/v1alpha3/experiment/condition.go
  pkg/controller/v1alpha3/experiment/event.go
  pkg/controller/v1alpha3/experiment/experiment_controller.go
  pkg/controller/v1alpha3/experiment/handle.go
  pkg/controller/v1alpha3/experiment/status.go
  pkg/controller/v1alpha3/recorder/recorder.go
  pkg/controller/v1alpha3/util/util.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#3 feat(trial): Add trial and metrics collector
  manifests/v1alpha3/crd/experiment.yaml
  manifests/v1alpha3/crd/suggestion.yaml
  manifests/v1alpha3/crd/trial.yaml
  manifests/v1alpha3/sample/trial.yaml
  pkg/api/operators/apis/addtoscheme_tfjob_v1beta2.go
  pkg/api/operators/apis/suggestion/v1alpha2/register.go
  pkg/api/operators/apis/trial/v1alpha2/trial_types.go
  pkg/api/operators/apis/trial/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/v1alpha3/trial/clientset/tf.go
  pkg/controller/v1alpha3/trial/clientset/unstructured.go
  pkg/controller/v1alpha3/trial/composer/composer.go
  pkg/controller/v1alpha3/trial/condition.go
  pkg/controller/v1alpha3/trial/event.go
  pkg/controller/v1alpha3/trial/handle.go
  pkg/controller/v1alpha3/trial/metricscollector/metricscollector.go
  pkg/controller/v1alpha3/trial/status.go
  pkg/controller/v1alpha3/trial/trial_controller.go
  pkg/controller/v1alpha3/util/util.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#4 feat(suggestion): Support advisor algorithms
  cmd/suggestion/v1alpha3/advisor/__init__.py
  cmd/suggestion/v1alpha3/advisor/unified.py
  pkg/api/suggestion/v1alpha3/advisor.pb.go
  pkg/api/suggestion/v1alpha3/advisor.proto
  pkg/api/suggestion/v1alpha3/advisor.swagger.json
  pkg/api/suggestion/v1alpha3/build.sh
  pkg/api/suggestion/v1alpha3/gen-doc/Dockerfile
  pkg/api/suggestion/v1alpha3/gen-doc/api.md
  pkg/api/suggestion/v1alpha3/gen-doc/index.html
  pkg/api/suggestion/v1alpha3/katib.pb.go
  pkg/api/suggestion/v1alpha3/katib.proto
  pkg/api/suggestion/v1alpha3/katib.swagger.json
  pkg/api/suggestion/v1alpha3/python/advisor_pb2.py
  pkg/api/suggestion/v1alpha3/python/advisor_pb2_grpc.py
  pkg/api/suggestion/v1alpha3/python/katib_pb2.py
  pkg/api/suggestion/v1alpha3/python/katib_pb2_grpc.py
  pkg/suggestion/v1alpha3/__init__.py
  pkg/suggestion/v1alpha3/advisor/__init__.py
  pkg/suggestion/v1alpha3/advisor/advisor.py
  pkg/suggestion/v1alpha3/advisor/algorithm/README.md
  pkg/suggestion/v1alpha3/advisor/algorithm/__init__.py
  pkg/suggestion/v1alpha3/advisor/algorithm/abstract_algorithm.py
  pkg/suggestion/v1alpha3/advisor/algorithm/abstract_algorithm_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/base_chocolate_algorithm.py
  pkg/suggestion/v1alpha3/advisor/algorithm/base_chocolate_algorithm_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/base_hyperopt_algorithm.py
  pkg/suggestion/v1alpha3/advisor/algorithm/base_hyperopt_algorithm_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/base_skopt_algorithm.py
  pkg/suggestion/v1alpha3/advisor/algorithm/base_skopt_algorithm_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/bayesian_optimization.py
  pkg/suggestion/v1alpha3/advisor/algorithm/bayesian_optimization_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/chocolate_bayes.py
  pkg/suggestion/v1alpha3/advisor/algorithm/chocolate_bayes_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/chocolate_grid_search.py
  pkg/suggestion/v1alpha3/advisor/algorithm/chocolate_grid_search_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/chocolate_random_search.py
  pkg/suggestion/v1alpha3/advisor/algorithm/chocolate_random_search_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/cmaes.py
  pkg/suggestion/v1alpha3/advisor/algorithm/cmaes_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/grid_search.py
  pkg/suggestion/v1alpha3/advisor/algorithm/grid_search_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/hyperopt_random_search.py
  pkg/suggestion/v1alpha3/advisor/algorithm/hyperopt_random_search_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/mocmaes.py
  pkg/suggestion/v1alpha3/advisor/algorithm/mocmaes_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/particle_swarm_optimization.py
  pkg/suggestion/v1alpha3/advisor/algorithm/particle_swarm_optimization_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/quasi_random_search.py
  pkg/suggestion/v1alpha3/advisor/algorithm/quasi_random_search_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/random_search.py
  pkg/suggestion/v1alpha3/advisor/algorithm/random_search_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/simulate_anneal.py
  pkg/suggestion/v1alpha3/advisor/algorithm/simulate_anneal_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/skopt_bayesian_optimization.py
  pkg/suggestion/v1alpha3/advisor/algorithm/skopt_bayesian_optimization_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/tpe.py
  pkg/suggestion/v1alpha3/advisor/algorithm/tpe_test.py
  pkg/suggestion/v1alpha3/advisor/algorithm/util.py
  pkg/suggestion/v1alpha3/advisor/algorithm/util_test.py
  pkg/suggestion/v1alpha3/test-client.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#7 feat(suggestion): Add suggestion controller
  manifests/v1alpha3/sample/suggestion.yaml
  pkg/controller/v1alpha3/recorder/recorder.go
  pkg/controller/v1alpha3/suggestion/clientset/deployment.go
  pkg/controller/v1alpha3/suggestion/condition.go
  pkg/controller/v1alpha3/suggestion/event.go
  pkg/controller/v1alpha3/suggestion/handle.go
  pkg/controller/v1alpha3/suggestion/status.go
  pkg/controller/v1alpha3/suggestion/suggestion_controller.go
  pkg/controller/v1alpha3/suggestion/util.go
  pkg/controller/v1alpha3/util/util.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
