Repository caicloud/katib, pull requests merged in 2021-01, with the labels that each got.

#23 feat(cert): update cert secret
  build/katib-controller/Dockerfile
  hack/gencerts.sh
  manifests/katib/templates/secret.yaml
  manifests/katib/templates/webhook-cleanup-job.yaml
  manifests/katib/templates/webhook-init-job.yaml
  manifests/katib/values.yaml
Labels: do-not-merge/release-note-label-needed, size/L

#24 chore(github): update pr & issues tpl
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, release-note-none, size/M

#25 fix(cm): cm typo bug
  Makefile
  manifests/katib/templates/configmap.yaml
Labels: lgtm, release-note-none, size/M

#26 feat(release): update manifest
  manifests/katib-controller/Chart.yaml
  manifests/katib-controller/crds/katib.yaml
  manifests/katib-controller/templates/_capabilities.tpl
  manifests/katib-controller/templates/_images.tpl
  manifests/katib-controller/templates/_labels.tpl
  manifests/katib-controller/templates/_names.tpl
  manifests/katib-controller/templates/_tplvalues.tpl
  manifests/katib-controller/templates/configmap.yaml
  manifests/katib-controller/templates/deployments.yaml
  manifests/katib-controller/templates/service.yaml
  manifests/katib-controller/templates/webhook-cleanup-job.yaml
  manifests/katib-controller/templates/webhook-init-job.yaml
  manifests/katib-controller/values.yaml
  manifests/katib-db-manager/Chart.yaml
  manifests/katib-db-manager/templates/_capabilities.tpl
  manifests/katib-db-manager/templates/_images.tpl
  manifests/katib-db-manager/templates/_labels.tpl
  manifests/katib-db-manager/templates/_names.tpl
  manifests/katib-db-manager/templates/_tplvalues.tpl
  manifests/katib-db-manager/templates/deployments.yaml
  manifests/katib-db-manager/templates/service.yaml
  manifests/katib-db-manager/values.yaml
  manifests/katib-db/Chart.yaml
  manifests/katib-db/templates/_configmap.tpl
  manifests/katib-db/templates/_container.tpl
  manifests/katib-db/templates/_daemonset.tpl
  manifests/katib-db/templates/_deployment.tpl
  manifests/katib-db/templates/_labels.tpl
  manifests/katib-db/templates/_pod.tpl
  manifests/katib-db/templates/_pvc.tpl
  manifests/katib-db/templates/_secret.tpl
  manifests/katib-db/templates/_statefulset.tpl
  manifests/katib-db/templates/_svc.tpl
  manifests/katib-db/templates/_tplvalues.tpl
  manifests/katib-db/templates/configmaps.yaml
  manifests/katib-db/templates/daemonsets.yaml
  manifests/katib-db/templates/deployments.yaml
  manifests/katib-db/templates/pvcs.yaml
  manifests/katib-db/templates/secrets.yaml
  manifests/katib-db/templates/statefulsets.yaml
  manifests/katib-db/templates/svcs.yaml
  manifests/katib-db/values.yaml
Labels: release-note-none, size/XL

#27 feat(mysql): update template
  manifests/katib-controller/Chart.yaml
  manifests/katib-db-manager/Chart.yaml
  manifests/katib-mysql/Chart.yaml
  manifests/katib-mysql/values.yaml
Labels: release-note-none
